
import UIKit

//MARK: Game questions
var gameQuestionsArray = [
    Question(text: "Возле какой горы-вулкана был впервые найден драгоценный камень танзанит?",
             answers: [Answer(text: "Фудзияма", correct: false),
                       Answer(text: "Ксудач", correct: false),
                       Answer(text: "Килиманджаро", correct: true),
                       Answer(text: "Эльбрус", correct: false)]),
    Question(text: "Какой головной убор был во время бала на Татьяне Лариной, героине романа «Евгений Онегин»?",
             answers: [Answer(text: "Желтая панама", correct: false),
                       Answer(text: "Ушанка", correct: false),
                       Answer(text: "Синий платок", correct: false),
                       Answer(text: "Малиновый берет", correct: true)]),
    Question(text: "Название какого алкогольного напитка переводится с немецкого как «полынь»?",
             answers: [Answer(text: "Коньяк", correct: false),
                       Answer(text: "Вермут", correct: true),
                       Answer(text: "Бурбон", correct: false),
                       Answer(text: "Самогон", correct: false)]),
//    Question(text: "Какое астрономическое явление жители Земли могут наблюдать раз в 75–76 лет?",
//             answers: [Answer(text: "Лунное затмение ", correct: false),
//                       Answer(text: "Световое эхо", correct: false),
//                       Answer(text: "Метеорный поток", correct: false),
//                       Answer(text: "Появление кометы Галлея", correct: true)]),
//    Question(text: "Скольким каратам соответствует чистое золото?",
//             answers: [Answer(text: "24-каратное золото", correct: true),
//                       Answer(text: "999 пробы", correct: false),
//                       Answer(text: "26-каратное золото", correct: false),
//                       Answer(text: "958 пробы", correct: false)]),
//    Question(text: "Какая из планет Солнечной системы самая горячая?",
//             answers: [Answer(text: "Коньяк", correct: false),
//                       Answer(text: "Солнце", correct: false),
//                       Answer(text: "Венера", correct: true),
//                       Answer(text: "Самогон", correct: false)]),
    Question(text: "Как называется красная тряпка в руках у матадора?",
             answers: [Answer(text: "Мулета", correct: true),
                       Answer(text: "Платок", correct: false),
                       Answer(text: "Бешенка", correct: false),
                       Answer(text: "Коррида", correct: false)])
    ]
