
import UIKit

//MARK: Game questions
var gameQuestionsArray = [
    Question(text: "Возле какой горы-вулкана был впервые найден драгоценный камень танзанит?",
             answers: [Answer(text: "Фудзияма", correct: false),
                       Answer(text: "Ксудач", correct: false),
                       Answer(text: "Килиманджаро", correct: true),
                       Answer(text: "Эльбрус", correct: false)]),
    Question(text: "Какой головной убор был во время бала на Татьяне Лариной, героине романа «Евгений Онегин»?",
             answers: [Answer(text: "Желтая панама", correct: false),
                       Answer(text: "Ушанка", correct: false),
                       Answer(text: "Синий платок", correct: false),
                       Answer(text: "Малиновый берет", correct: true)]),
    Question(text: "Название какого алкогольного напитка переводится с немецкого как «полынь»?",
             answers: [Answer(text: "Коньяк", correct: false),
                       Answer(text: "Вермут", correct: true),
                       Answer(text: "Бурбон", correct: false),
                       Answer(text: "Самогон", correct: false)]),
    Question(text: "Какое астрономическое явление жители Земли могут наблюдать раз в 75–76 лет?",
             answers: [Answer(text: "Лунное затмение ", correct: false),
                       Answer(text: "Световое эхо", correct: false),
                       Answer(text: "Метеорный поток", correct: false),
                       Answer(text: "Появление кометы Галлея", correct: true)]),
    Question(text: "Скольким каратам соответствует чистое золото?",
             answers: [Answer(text: "24-каратное золото", correct: true),
                       Answer(text: "999 пробы", correct: false),
                       Answer(text: "26-каратное золото", correct: false),
                       Answer(text: "958 пробы", correct: false)]),
    Question(text: "Какая из планет Солнечной системы самая горячая?",
             answers: [Answer(text: "Солнце", correct: false),
                       Answer(text: "Плутон", correct: false),
                       Answer(text: "Венера", correct: true),
                       Answer(text: "Марс", correct: false)]),
    Question(text: "Как называется красная тряпка в руках у матадора?",
             answers: [Answer(text: "Мулета", correct: true),
                       Answer(text: "Платок", correct: false),
                       Answer(text: "Бешенка", correct: false),
                       Answer(text: "Коррида", correct: false)]),
    Question(text: "Какой элемент периодической таблицы имеет химический символ 'He'?",
                answers: [Answer(text: "Гелий", correct: true),
                          Answer(text: "Гидроген", correct: false),
                          Answer(text: "Гафний", correct: false),
                          Answer(text: "Гадолиний", correct: false)]),
       
       Question(text: "Какой самый крупный материк на планете Земля?",
                answers: [Answer(text: "Евразия", correct: true),
                          Answer(text: "Австралия", correct: false),
                          Answer(text: "Африка", correct: false),
                          Answer(text: "Антарктида", correct: false)]),
       
       Question(text: "Кто написал роман 'Война и мир'?",
                answers: [Answer(text: "Александр Дюма", correct: false),
                          Answer(text: "Федор Достоевский", correct: false),
                          Answer(text: "Лев Толстой", correct: true),
                          Answer(text: "Иван Тургенев", correct: false)]),
       
       Question(text: "Как называется самая высокая гора на Земле?",
                answers: [Answer(text: "МакКинли", correct: false),
                          Answer(text: "Эверест", correct: true),
                          Answer(text: "Килиманджаро", correct: false),
                          Answer(text: "К2", correct: false)]),
       
       Question(text: "Сколько планет в нашей Солнечной системе?",
                answers: [Answer(text: "9", correct: false),
                          Answer(text: "10", correct: false),
                          Answer(text: "8", correct: true),
                          Answer(text: "7", correct: false)])
    ]
